rumqttd_config = "./server/rumqttd.toml"

[[plugins]]
name = "doubler"
file = "./double_plugin.wasm"
in_topic = "demo/doubler"
out_topic = "demo/doubled"

[[plugins]]
name = "other-doubler"
file = "./double_plugin.wasm"
in_topic = "demo/doubler"
out_topic = "demo/doubled"
