[package]
name = "server"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
config = "0.13.3"
extism = "0.3.0"
pretty_env_logger = "0.4.0"
rumqttd = "0.14.0"
tracing-subscriber = "0.3.16"
